### ISSUE TITLE
Roadmap to v1.1

### ISSUE THREAD

**Issue by coolaj86** [digitalcashdev/RPCWebProxy#2]
About v1.1-ish
- [x] add links to RPC docs and this repos issues
- [ ] create machine-readable (JSON) RPC docs
- [ ] create machine-readable (JSON) examples that auto-populate
- [ ] add `--config` option that defaults to `~/.config/dash-rpcproxy/env`
- [ ] add `PORT` to complement `--port` and update `example.env`
- [ ] add `version, --version, -V` and `help`
- [ ] publish with `goreleaser`

About v1.2 or so
- [x] automatically update `dashd` to latest on `dashd-1.local`
- [ ] require action to update `dashd-2.local`, keeping it "stable"
- [ ] use the pattern of `/wallet/edge` or `/wallet/stable` to route in proxy (maintains compat with legacy clients)
- [ ] different theme colors for different stability

Maybe v1.5
- [ ] JS example to self-sign JWT with secp256k1
- [ ] Raise rate limit if the verified public key produces an address with the required balance, ex:
       - 0.1 DASH => 1,000 requests per day
       - 1.0 DASH => 10,000 requests per day
       - etc
- [ ] require api key for non-edge
